### ISSUE TITLE
workspace not binding

### ISSUE THREAD

**Issue by shohagrana64** [bigkevmcd/tekton-polling-operator#8]
Workspace declared as follows:
```
apiVersion: polling.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: example-repository
spec:
  url: https://github.com/shohagrana64/java-hello-world-with-maven.git
  ref: master
  frequency: 1m
  type: github
  pipelineRef:
    name: demo-pipeline
    params:
    workspaces:
      - name: source
        persistentVolumeClaim:
          claimName: buildah-pvc-rana
```
I have created the pvc.
my task uses workspace source which is supposed to be given by the pipelinerun. But it is not binding correctly. The error is:
```PipelineRun default/polled-pipelinerun-8k6vv doesn't bind Pipeline default/demo-pipeline's Workspaces correctly: pipeline requires workspace with name "source" be provided by pipelinerun```

**Comment by shohagrana64** [comment]
I used the latest release 0.4.0

**Comment by bigkevmcd** [comment]
Hi Shohaq,

I'm looking into it, not quite sure what's going on, but it also looks like
Docker hub removed the image.

I will update the ticket when I know more.

Kevin

**Comment by bigkevmcd** [comment]
I've written an example in here https://github.com/bigkevmcd/tekton-polling-operator/tree/main/examples/workspace that might help.

**Comment by shohagrana64** [comment]
Thank you for the example. This is exactly how I configured the workspace. Sadly, I am getting the same error
```
apiVersion: polling.tekton.dev/v1alpha1
kind: Repository
metadata:
  name: example-repository
spec:
  url: https://github.com/shohagrana64/java-hello-world-with-maven.git
  ref: master
  frequency: 1m
  type: github
  pipelineRef:
    name: demo-pipeline
    params:
    workspaces:
      - name: source
        persistentVolumeClaim:
          claimName: buildah-pvc-rana
```
you can see my demo pipeline here:
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline
spec:
  workspaces:
    - name: source
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: https://github.com/shohagrana64/java-hello-world-with-maven.git
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "master"
```
Also my pvc:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-pvc-rana
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```
